Update dockerfile

diff --git a/SellPhoneMvcUI/dockerfile b/SellPhoneMvcUI/dockerfile
--- a/SellPhoneMvcUI/dockerfile
+++ b/SellPhoneMvcUI/dockerfile
@@ -5,6 +5,7 @@ WORKDIR /src
 # Sao chép và kiểm tra tệp .csproj
 COPY *.csproj ./
 RUN ls -la  # Kiểm tra xem tệp .csproj có được sao chép không
+RUN if [ -z "$(ls -A *.csproj)" ]; then echo "ERROR: No .csproj files found!"; exit 1; fi
 RUN dotnet restore -v detailed
 
 # Sao chép mã nguồn và xuất bản
